<?php

namespace ContainerNbcFokz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BQcS4jRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bQcS4jR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bQcS4jR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\ArticleController::list' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\ArticleController::list()', 'getArticleControllerlistService', true],
            'App\\Controller\\ArticleController::new' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\ArticleController::new()', 'getArticleControllernewService', true],
            'App\\Controller\\ArticleController::show' => ['privates', '.service_locator.s9vRU66.App\\Controller\\ArticleController::show()', 'getArticleControllershowService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\ArticleController:list' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\ArticleController::list()', 'getArticleControllerlistService', true],
            'App\\Controller\\ArticleController:new' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\ArticleController::new()', 'getArticleControllernewService', true],
            'App\\Controller\\ArticleController:show' => ['privates', '.service_locator.s9vRU66.App\\Controller\\ArticleController::show()', 'getArticleControllershowService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\ArticleController::list' => '?',
            'App\\Controller\\ArticleController::new' => '?',
            'App\\Controller\\ArticleController::show' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\ArticleController:list' => '?',
            'App\\Controller\\ArticleController:new' => '?',
            'App\\Controller\\ArticleController:show' => '?',
        ]);
    }
}
