<?php

namespace ContainerZurzfy8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0DDT9rXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0DDT9rX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0DDT9rX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'article' => ['privates', '.errored..service_locator.0DDT9rX.App\\Entity\\Article', NULL, 'Cannot autowire service ".service_locator.0DDT9rX": it needs an instance of "App\\Entity\\Article" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'em' => '?',
            'article' => 'App\\Entity\\Article',
        ]);
    }
}
