<?php

namespace ContainerZurzfy8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.s9vRU66.App\Controller\ArticleController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.s9vRU66.App\\Controller\\ArticleController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'article' => ['privates', '.errored..service_locator.s9vRU66.App\\Entity\\Article', NULL, 'Cannot autowire service ".service_locator.s9vRU66": it needs an instance of "App\\Entity\\Article" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'article' => 'App\\Entity\\Article',
        ]))->withContext('App\\Controller\\ArticleController::show()', $container);
    }
}
