<?php

namespace Container2MjPpPA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleControllernewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.z0A7H.F.App\Controller\ArticleController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.z0A7H.F.App\\Controller\\ArticleController::new()'] = ($container->privates['.service_locator.z0A7H.F'] ?? $container->load('get_ServiceLocator_Z0A7H_FService'))->withContext('App\\Controller\\ArticleController::new()', $container);
    }
}
