<?php

namespace ContainerI1aKFvI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.0DDT9rX.App\Entity\Article' shared service.
     *
     * @return \App\Entity\Article
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.0DDT9rX": it needs an instance of "App\\Entity\\Article" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
