<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLqvv53V\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLqvv53V/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLqvv53V.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLqvv53V\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLqvv53V\App_KernelDevDebugContainer([
    'container.build_hash' => 'Lqvv53V',
    'container.build_id' => '594bd81f',
    'container.build_time' => 1768236838,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLqvv53V');
