<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2MjPpPA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2MjPpPA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2MjPpPA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2MjPpPA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2MjPpPA\App_KernelDevDebugContainer([
    'container.build_hash' => '2MjPpPA',
    'container.build_id' => '306785a6',
    'container.build_time' => 1766500661,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container2MjPpPA');
